# Constant fieldnames concerning stations
CODE = "Kod stacji"
INTERNATIONAL_CODE = "Kod międzynarodowy"
NAME = "Nazwa stacji"
OLD_CODE = "Stary Kod stacji (o ile inny od aktualnego)"
LAUNCH_DATE = "Data uruchomienia"
CLOSE_DATE = "Data zamknięcia"
STATION_TYPE = "Typ stacji"
AREA_TYPE = "Typ obszaru"
STATION_KIND = "Rodzaj stacji"
VOIVODESHIP = "Województwo"
CITY = "Miejscowość"
ADDRESS = "Adres"
LATITUDE = "WGS84 φ N"
LONGITUDE = "WGS84 λ E"